### PR TITLE
Add Crystallize platform

### PR DESCRIPTION
**Pull request by danisal**
This Pull Request is to add Crystallize as a solution

### CODE REVIEW

**Comment by michaelbromley** [comment]
Hi!
Thank you so much for your contribution! Can you give me a bit more context about what is meant by "Full support for custom-built solution"? I thought it is pure SaaS - do you also have a self-hosted option?

**Comment by danisal** [comment]
hey @michaelbromley , you're right, we're a SaaS company, with the "Full support for custom-built solution" we want to mean that users can come up with a "plugin" (which might not be the final term) and/or an app that might integrate with Crystallize. 

Would you prefer to have a better description?

**Comment by michaelbromley** [comment]
OK thanks. The support level is really about what is supported out-of-the-box. If there already _is_ an existing plugin (free or commercial), then you should choose "free-extension" or "paid-extension". If nothing yet exists, but _could_ be implemented in theory, then leave it as "none", since I want to give merchants an overview of _what the base capabilities of each platform are_.

Now that you are the first SaaS entry, I'll make some changes so that we can list properties at the top more relevant to a SaaS (e.g. framework and license are not important for SaaS, although cool to see you are built on NestJS!). 

But I can do that work after merging your PR. Do you have any suggestions of what kinds of properties would be more relevant for SaaS instead of "language", "license", "underlying framework" and "supported databases"? I need inspiration on that!

**Comment by danisal** [comment]
Thanks for the input and help Michael! What about features that are built into our free & open boilerplates? We have a standalone plug-in system, but you would not add most of these features through a plugin, free or paid. You’d interface with them via our main platform , and the front-end examples are free. 

Each feature found in our boilerplates is fully supported.  Would “Available and fully supported in our open boilerplates” be a better way to explain it?

I will think about the suggestions and follow up with some ideas!

**Comment by michaelbromley** [comment]
OK thanks for the explanation. Yeah, so it sounds like it would be accurate to list as "partial" with that note on the boilerplates. Would you agree with that?

**Comment by danisal** [comment]
yeah, make sense, going to update the PR

**Pull request merged**
